<?php
$merchant_code = $this->getData('merchant_code');
$tokenGUID = $this->getData('tokenGUID');
$action_gateway = $this->getData('action_gateway');

// Retrieve order
$_order = Mage::getModel('sales/order');
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);

// save generated token to the current order
$payment = $_order->getPayment();
$payment->setAdditionalData($tokenGUID)
->save();

$_order->setState(Mage_Sales_Model_Order::STATE_PENDING_PAYMENT, true, 'Order token: ' . $tokenGUID);

$total = round($_order->getBaseGrandTotal(), 2);
$shipping_amount = $_order->getShippingAmount();


// Convert currency to SAR
$total = round(Mage::helper('directory')->currencyConvert($total, 'USD', 'SAR'), 2);
$shipping_amount = round(Mage::helper('directory')->currencyConvert($_order->getShippingAmount(), 'USD', 'SAR'), 2);

// testing amount
$test_mode = Mage::getStoreConfig('payment/faturah/sandbox_mode');
/*if($test_mode) {
	$total = 1.00;
	$shipping_amount = 0.00;
} else {
	// Convert currency to SAR
	$total = round(Mage::helper('directory')->currencyConvert($total, 'USD', 'SAR'), 2);
	$shipping_amount = round(Mage::helper('directory')->currencyConvert($_order->getShippingAmount(), 'USD', 'SAR'), 2);
}*/


$items_name = array();
$items_description = array();
$items_qty = array();
$items_price = array();
$items_id = array();

$items = $_order->getAllItems();

foreach ($items as $item) {
	$product = Mage::getModel('catalog/product')->load($item->getProductId());
	$items_name[] = $product->getName();
    $items_description[] = substr(htmlentities($product->getDescription()), 0, 50);
    $items_qty[] = $item->getQtyOrdered();
    /*if($test_mode) {
		$items_price[] = round(1, 2);
	} else {
		$items_price[] = round(Mage::helper('directory')->currencyConvert(round($item->getPrice(), 2), 'USD', 'SAR'), 2);
	}*/
    $items_price[] = round(Mage::helper('directory')->currencyConvert(round($item->getPrice(), 2), 'USD', 'SAR'), 2);
    $items_id[] = $item->getProductId();
}

?>


<form name="faturahpaymentform" action="<?php echo $action_gateway ?>" method="post">
    <input type="hidden" name="mc" value="<?php echo $merchant_code ?>" />
    <input type="hidden" name="mt" value="<?php echo $tokenGUID ?>" />
    <input type="hidden" name="dt" value="<?php echo date('m/d/Y h:i:s A') ?>" />
    <input type="hidden" name="a" value="<?php echo $total ?>" />
<!--
    <input type="hidden" name="DeliveryCharge" value="<?php echo $shipping_amount ?>" />
-->
    <input type="hidden" name="DeliveryCharge" value="<?php echo 0 ?>" />
    <input type="hidden" name="ProductID" value="<?php echo implode("|", $items_id) ?>" />
    <input type="hidden" name="ProductName" value="<?php echo implode("|", $items_name) ?>" />
    <input type="hidden" name="ProductQuantity" value="<?php echo implode("|", $items_qty) ?>" />
    <input type="hidden" name="ProductDescription" value="<?php echo implode("|", $items_description) ?>" />
    <input type="hidden" name="ProductPrice" value="<?php echo implode("|", $items_price) ?>" />
    <input type="hidden" name="EMail" value="<?php echo $_order->getCustomerEmail() ?>" />
    <input type="hidden" name="lang" value="en" />
</form>
<script type="text/javascript">
	document.faturahpaymentform.submit();
</script>
